name: Laravel Database Migration

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  migrate_database:
    name: Migrate Database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Specify your PHP version here

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

    

      - name: Run Laravel migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 198.251.84.200
          DB_PORT: 3306
          DB_DATABASE: your_database_name
          DB_USERNAME: biraj_test_admin
          DB_PASSWORD: Biraj@224973
