name: Deploy Laravel Project on Push

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3
     
      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, zip, dom

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate Laravel Mix
        run: npm install

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.rajphotopasal.com
          username: portfolio@birajshrestha.com.np
          password: Biraj@224973

  migrate-and-seed:
    name: Migrate and Seed Database
    runs-on: ubuntu-latest
    needs: web-deploy
    env:
      DB_CONNECTION: pgsql
      DB_DATABASE: biraj_db_portfolio
      DB_PORT: 5432
      DB_USERNAME: biraj_portfolio_admin
      DB_PASSWORD: Biraj@224973
    steps:
      - name: 🚀 Run Migrations and Seeding
        run: |
          cd /my-sites/portfolio
          php artisan migrate:fresh --seed
