name: Laravel Database Migration

on:
  push:
    branches:
      - main
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --no-progress --no-suggest
        
        
      - name: Database migration
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 198.251.84.200
          DB_PORT: 3306
          DB_DATABASE: biraj_db_test
          DB_USERNAME: biraj_test_admin
          DB_PASSWORD: "Biraj@224973"
