name: Deploy Laravel App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Laravel App
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: biraj_portfolio_admin
          POSTGRES_PASSWORD: H;x(FY[{5^Rw
          POSTGRES_DB: biraj_db_portfolio
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy .env File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Wait for PostgreSQL to be ready
        run: |
          until nc -z -v -w30 http://c3.my-control-panel.com 5432
          do
            echo "Waiting for PostgreSQL..."
            # wait for 5 seconds before checking again
            sleep 5
          done

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Seed Database
        run: php artisan db:seed --force
