name: Laravel Migration

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run PHP Artisan migrate
        run: |
          ssh biraj@hc3.my-control-panel.com "cd /home/my-sites/portfolio && php artisan migrate"
