name: Deploy Laravel App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install dependencies, including FTP deployment tool
      - name: Install PHP and FTP Deploy Tool
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
        run: |
          sudo apt-get install -y lftp

      # Set up environment variables from .env file
      - name: Set up environment variables
        run: |
          echo "APP_ENV=production" >> $GITHUB_ENV
          echo "APP_KEY=" >> $GITHUB_ENV
          echo "APP_DEBUG=false" >> $GITHUB_ENV
          # Add more variables as needed

          # Read database credentials from .env file
          export $(grep -v '^#' .env | xargs -d '\n')

          # Set database credentials as environment variables
          echo "DB_CONNECTION=${DB_CONNECTION}" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_DATABASE=biraj_db_portfolio" >> $GITHUB_ENV
          echo "DB_USERNAME=biraj_portfolio_admin" >> $GITHUB_ENV
          echo "DB_PASSWORD=Biraj@224973" >> $GITHUB_ENV

      # Run database migrations and seeding
      - name: Run Migrations and Seed Database
        run: |
          echo "Running migrations..."
          php artisan migrate
          echo "Migrations completed."

          echo "Seeding database..."
          php artisan db:seed
          echo "Seeding completed."
